### ISSUE TITLE
The result of Seq2Seq

### ISSUE THREAD

**Issue by JBoRu** [gmftbyGMFTBY/MultiTurnDialogZoo#4]
Thanks for your amazing work ! Recently, i modify seq2seq-attn model based on Pytorch Chatbot Tutorial and train a baseline for DailyDialog, but i can't train it successfully no matter how i change the parameters, and i use your code, but still get a poor result as follows, can you give me a help ?
![image](https://user-images.githubusercontent.com/38073482/80605161-47411900-8a65-11ea-8969-2797552840b0.png)

**Comment by gmftbyGMFTBY** [comment]
Hi, how many epochs do you use?

**Comment by JBoRu** [comment]
> Hi, how many epochs do you use?

Hi, I not change the parameters,  i just run the code. So for the difference model type, how should i change the parameters ? Looking forward your reply !

**Comment by gmftbyGMFTBY** [comment]
That looks strange, in my experiments, the Seq2Seq can generate good responses.
You can find the way to change the model in the `README`.

**Comment by JBoRu** [comment]
> That looks strange, in my experiments, the Seq2Seq can generate good responses.
> You can find the way to change the model in the `README`.
