### ISSUE TITLE
The dataset only have 3 file instead 6 file.

### ISSUE THREAD

**Issue by RyanLee-Dev** [gmftbyGMFTBY/MultiTurnDialogZoo#5]
I download the data from your link, but only 'dial.test' 'dial.train' 'dial.valid'.

**Comment by gmftbyGMFTBY** [comment]
actually, you can find the corresponding data-processing file in the folder: `data/data_process`

**Comment by RyanLee-Dev** [comment]
Thanks very much, I missed.

**Comment by RyanLee-Dev** [comment]
老哥，咨询一下，为啥我train的显存只用了4G，哪个参数能把显卡跑满呢？

**Comment by gmftbyGMFTBY** [comment]
可以试着加大batch size
